### PR TITLE
STCLI-216: Add stripes-webpack as choice for workspace "other"

### PR DESCRIPTION
**Pull request by ncovercash**
Resolves [Jira STCLI-216](https://issues.folio.org/projects/STCLI/issues/STCLI-216?filter=allissues) by adding `stripes-webpack` to the list of available packages

### CODE REVIEW

**Comment by ncovercash** [comment]
@zburke would you please review this?

**Comment by ncovercash** [comment]
Ah, it's in a fork, so sonar can't run on it.  Feel free to copy the branch in and make a new PR for that, if needed.

**Review by zburke — APPROVED** [review]
LGTM

**Comment by zburke** [comment]
@ncovercash: coupla things:
1. Please do your work on a feature branch. You're right the Sonar check on this PR failed because it's from a fork, but if you had commit privileges here it would have failed even earlier (at the `git push` stage) because in `folio-org` `#master` is a protected branch that you can only merge to via PR, not via direct commit. 
2. Personally, I'm a little wary of using `stripes-cli` to create workspaces, even though we built that functionality, because it means you need to install it globally. This in turn means that `stripes foo` (leveraging the global install) is likely to use a different version than `yarn stripes foo` (leveraging a cloned repo's local install). This doesn't mean global installs are bad. Maybe `stripes foo` and `yarn stripes foo` will behave identically (yay!), but maybe not if you have an ancient global install that you've forgotten to update.

**Comment by ncovercash** [comment]
@zburke ah thanks, didn't catch it went in the fork's master – was doing a quick fix through GitHub directly.

Totally get the version mismatch issue with creating workspaces, but I thought [this was the preferred method](https://github.com/folio-org/stripes/blob/master/doc/new-development-setup.md#create-your-workspace)?  Is there another method documented somewhere?

**Pull request merged**
