### PR TITLE
Correct Okapi syntax for optional dependencies

### PR DESCRIPTION
**Pull request by MikeTaylor**
Fixes FOLIO-2570.

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
Has the generated descriptor been successfully registered with an instance of Okapi?

**Comment by MikeTaylor** [comment]
> Has the generated descriptor been successfully registered with an instance of Okapi?

Not by me; I don't run by own Okapi at all.

**Comment by MikeTaylor** [comment]
What of we just merge another (trivial) commit to ui-tenant-settings. That should kick off the build process again, including the part that failed last time, giving rise to FOLIO-2570.

Does anyone (@wafschneider @funkymalc @ihardy) know which version of stripes-cli Jenkins uses for its `publishModDescriptor=true` rule? If we merge this PR will that suffice for the new head of `master` to be used?

**Comment by MikeTaylor** [comment]
At any rate, I can't think of any reason not to go ahead and merge this. It passes all tests, and it generates the exact same module-descriptor output as before for packages with no `optionalOkapiInterfaces`. So the worst case would be that it _still_ doesn't generate the right module-descriptor output for packages that _do_ have `optionalOkapiInterfaces`, and that would be no worse than what we have now.

**Comment by zburke** [comment]
The ui-tenant-settings PR that touched this off still shows the same, incorrect MD as before, suggesting we actually need a release here. I'll publish it once I get out of meetings.

**Comment by dcrossleyau** [comment]
Fixed. See [FOLIO-2572](https://issues.folio.org/browse/FOLIO-2572) which deployed a new jenkins-slave-all build image, which includes the new stripes-cli v1.5.1

Hence publishing MDs with optionalOkapiInterfaces can proceed. Verified with [ui-tenant-settings](https://github.com/folio-org/ui-tenant-settings/commits/master).

**Pull request merged**
