### PR TITLE
STCLI-142 support additional apps/libraries

### PR DESCRIPTION
**Pull request by zburke**
Provide support for additional apps and libraries.

Refs [STCLI-142](https://issues.folio.org/browse/STCLI-142)

### CODE REVIEW

**Comment by zburke** [comment]
Do I have `stripes` in the right place? It's not typical to have it cloned in a workspace, but if you do (e.g. because you're the package maintainer and you need to tweak it and then you forget it's there and then somebody else tweaks it and then you run `stripes platform pull; stripes platform build` but that didn't know about `stripes` so now you have two copies of some of its libraries in your build and WTF?!?!1!!) it's crucial to keep it up to date.

**Comment by ttamj** [comment]
> Do I have stripes in the right place?

Sorry I missed your question when I added the review. Let me give that some thought.

**Comment by zburke** [comment]
I don't see any major issues with STCLI-122. There's an [official client](https://github.com/octokit/rest.js/) that looks to make it trivial to retrieve a list we could then filter by prefix (`stripes-`, `ui-`). That feels brittle, but I'm not sure it's really a problem. 
```
const Octokit = require('@octokit/rest')
const octokit = new Octokit()

// Compare: https://developer.github.com/v3/repos/#list-organization-repositories
octokit.repos.listForOrg({
  org: 'octokit',
  type: 'public'
}).then(({ data }) => {
  // handle data
})
```

**Comment by ttamj** [comment]
I think listing `stripes` under `otherModules` is the right thing here.  Doing this gets it included in the [`allModules` export](https://github.com/folio-org/stripes-cli/blob/a2351fc2c5abcc71a291540419e870a62b24cfed/lib/environment/inventory.js#L95) which is sufficient to pass the `validateModules` test when [scanning a workspace directory](https://github.com/folio-org/stripes-cli/blob/a2351fc2c5abcc71a291540419e870a62b24cfed/lib/environment/development.js#L56-L60) for platform commands.

By not including `stripes` under `stripesModules`, it perhaps has less visibility, which I think is good. Most folks probably shouldn't be cloning it locally anyway.

On a related note, have you considered using separate workspace for `stripes` maintenance?  One where you have only `stripes` and `stripes-*` modules "open" at the time.  This allows your original workspace to reflect that of _consumer_ of stripes where you leave the stripes modules "closed" by not cloning them.

**Comment by zburke** [comment]
> using separate workspace for stripes maintenance

Good thinking.

**Pull request merged**
